#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate compiled display defaults adapter header from a template or personal header."""

import os
from pathlib import Path
import re
import sys

SCHEMA_RE = re.compile(r"#\s*define\s+HAX_DEFAULTS_SCHEMA\s+([0-9]+)")
DEF_RE = re.compile(r"#\s*define\s+(HAX_DEFAULT_[A-Z_]+)\s+\"([^\"]*)\"")

SHIPPED_DEFAULTS = {
    "HAX_DEFAULT_MARKDOWN": "1",
    "HAX_DEFAULT_DISPLAY_WIDTH": "auto",
    "HAX_DEFAULT_THEME": "auto",
    "HAX_DEFAULT_TINT": "teal",
}

VALID_CHOICES = {
    "HAX_DEFAULT_MARKDOWN": {"1", "0", "true", "false", "on", "off"},
    "HAX_DEFAULT_THEME": {"auto", "dark", "light", "ansi", "off"},
    "HAX_DEFAULT_TINT": {"teal", "violet", "rose", "sage"},
}


def validate_display_width(val: str) -> None:
    if val in ("auto", "terminal"):
        return
    try:
        w = int(val)
        if w < 20:
            raise ValueError()
    except ValueError:
        raise ValueError(f"invalid HAX_DEFAULT_DISPLAY_WIDTH: '{val}' (must be auto, terminal, or integer >= 20)")


def main():
    if len(sys.argv) != 4:
        print("usage: generate_defaults.py <source_root> <header_option> <output_header>", file=sys.stderr)
        sys.exit(2)

    source_root = Path(sys.argv[1])
    header_opt = sys.argv[2]
    out_path = Path(sys.argv[3])

    if header_opt:
        header_path = Path(header_opt)
        if not header_path.is_absolute():
            header_path = source_root / header_path
        if not header_path.is_file():
            print(f"error: selected personal defaults header '{header_path}' does not exist", file=sys.stderr)
            sys.exit(1)
    else:
        header_path = source_root / "config.def.h"

    content = header_path.read_text(encoding="utf-8")
    schema_match = SCHEMA_RE.search(content)
    if not schema_match:
        print(f"error: missing HAX_DEFAULTS_SCHEMA macro in '{header_path}'", file=sys.stderr)
        sys.exit(1)
    schema_ver = int(schema_match.group(1))
    if schema_ver != 1:
        print(f"error: unsupported HAX_DEFAULTS_SCHEMA {schema_ver} in '{header_path}'; expected 1", file=sys.stderr)
        sys.exit(1)

    resolved = dict(SHIPPED_DEFAULTS)
    for k, v in DEF_RE.findall(content):
        if k in resolved:
            resolved[k] = v

    # Validation gate
    for k, choices in VALID_CHOICES.items():
        val = resolved[k]
        if val not in choices:
            print(f"error: invalid {k} value '{val}'; must be one of {sorted(choices)}", file=sys.stderr)
            sys.exit(1)

    try:
        validate_display_width(resolved["HAX_DEFAULT_DISPLAY_WIDTH"])
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    out_content = [
        "/* SPDX-License-Identifier: MIT */",
        "/* Generated by scripts/generate_defaults.py. Do not edit directly. */",
        "#ifndef HAX_COMPILED_DEFAULTS_H",
        "#define HAX_COMPILED_DEFAULTS_H",
        "",
        "#define HAX_DEFAULTS_SCHEMA 1",
        "",
    ]
    for k, v in resolved.items():
        out_content.append(f'#define {k} "{v}"')
    out_content.append("")
    out_content.append("#endif /* HAX_COMPILED_DEFAULTS_H */\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out_content), encoding="utf-8")


if __name__ == "__main__":
    main()
